### ISSUE TITLE
error in fixseed

### ISSUE THREAD

**Issue by hansunggim** [TimothyADavis/KinMSpy#15]
Dear Timothy Davis et al. 

  I followed the fitting tutorial to learn how to use the KinMS but had an error when running it. The error was occurred with the fixseed=True in the In [9] which I attached below. The error message is 

  File "<string>", line 29, in make_model
TypeError: __init__() got an unexpected keyword argument 'fixseed'

In the tutorial, you noted that fixseed=True is crucial to fit the model to the data. Could you please help me how to solve this error?

Sincerely,
Hansung Gim

In [9]:
def make_model(param,obspars,rad,filename=None,plot=False):
    '''
    This function takes in the `param` array (along with obspars; the observational setup,
    and a radius vector `rad`) and uses it to create a KinMS model.
    '''
    
    total_flux=param[0]
    posAng=param[1]
    inc=param[2]
    v_flat=param[3]
    r_turn=param[4]
    scalerad=param[5]
    
    ### Here we use an exponential disk model for the surface brightness of the gas ###
    sbprof = np.exp((-1)*rad/scalerad)

    ### We use a very simple arctan rotation curve model with two free parameters. ###
    vel=(v_flat*2/np.pi)*np.arctan(rad/r_turn)

    ### This returns the model
    return KinMS(obspars['xsize'],obspars['ysize'],obspars['vsize'],obspars['cellsize'],obspars['dv'],\
                 obspars['beamsize'],inc,sbProf=sbprof,sbRad=rad,velRad=rad,velProf=vel,\
                 intFlux=total_flux,posAng=posAng,fixSeed=True,fileName=filename).model_cube(toplot=plot)

**Comment by TimothyADavis** [comment]
Hi Hansung,

One thing to check, as in the example code you posted at the end the parameter is case sensitive- it needs to be fixSeed=True. Does that fix your issue? I quickly tried copy+pasting the code exactly as written (i.e. with fixSeed rather than fixseed) and it seems to work?

Cheers,
Tim
Ps. You may be interested to check out https://github.com/TimothyADavis/KinMS_fitter if you are just starting out with KinMS - its a powerful wrapper for KinMS to help you get started fitting datacubes quickly+easily.

**Comment by hansunggim** [comment]
Hi Tim, 

  Many thanks for your quick response. 
  Yes, I figured out what was problem. As you told, I have written as fixseed=True mistakenly. I changed it to fixSeed=True and found it works. I was sorry for bothering you. 

  Also, thank you so much for suggesting another program. I will check it out. 

Sincerely, 
Hansung
